# Generated by Django 4.2.7 on 2023-12-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('base_clock', models.FloatField()),
                ('boost_clock', models.FloatField()),
                ('cache', models.CharField(max_length=255)),
                ('socket', models.CharField(max_length=50)),
                ('power_draw', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
